image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
  - init: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked
      npm install -g typescript
      npm install @coral-xyz/anchor @solana/web3.js
    command: anchor test --provider.cluster https://api.devnet.solana.com